version: "3.8"

services:
  app:
    container_name: RelayApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6007:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    command: npm run server
