version: "3.8"

services:
  node:
    container_name: NodeApp
    image: dudkinta/tgbc:latest
    pull_policy: always
    ports:
      - "6006:6006"
      - "3006:3006"
    environment:
      NODE_ENV: production
    command: npm run start
