services:
  node:
    container_name: NodeApp-1
    image: dudkinta/tgbc:latest
    pull_policy: always
    ports:
      - "3001:3001"
      - "6001:6001"
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: production
    command: sh -c "npm run build && npm run start"
