services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: blockchain_db
    volumes:
      - ./data/testnet/db:/var/lib/postgresql/data
