export const TYPES = {
    App: Symbol.for('App'),
    P2PClient: Symbol.for('P2PClient'),
    SystemCoordinator: Symbol.for('SystemCoordinator'),
    ConfigLoader: Symbol.for("ConfigLoader"),
    NetworkService: Symbol.for("NetworkService"),
    Delegator: Symbol.for("Delegator"),
    WebServer: Symbol.for("WebServer"),
    DbContext: Symbol.for("DbContext"),
    BlockChain: Symbol.for("BlockChain"),
    BlockChainRoutesFactory: Symbol.for("BlockChainRoutesFactory"),
    WalletRoutesFactory: Symbol.for("WalletRoutesFactory"),
    MessagesServiceFactory: Symbol.for("MessagesServiceFactory"),
    p2pClientHelper: Symbol.for("p2pClientHelper"),
};